version: "3.9"

networks:
  backend:
    driver: bridge

services:
  devcontainer:
    container_name: annoflow-vscode
    image: "ghcr.io/ulfsoft-harbour/dotnet/web-sdk-vscode:6.0-20220703.6"
    networks:
      - backend
    ports:
      - "5000:5000"
      - "5001:5001"
      - "443:443"
      - "80:80"
    volumes:
      - "../:/workspace:delegated"
      - "~/.gitconfig:/home/vscode/.gitconfig:ro"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
